# Generated by Django 2.1.2 on 2018-10-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 11, 7, 3, 398648)),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 7, 3, 398648)),
        ),
    ]
