# Generated by Django 2.1.2 on 2018-10-17 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_auto_20181018_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 0, 33, 46, 385384)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 0, 33, 46, 384384)),
        ),
    ]
