# Generated by Django 2.1.2 on 2018-10-18 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_auto_20181018_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 12, 22, 26, 37274)),
        ),
    ]
