# Generated by Django 2.1.2 on 2018-10-19 12:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_auto_20181019_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bidder',
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 15, 17, 52, 286481)),
        ),
        migrations.AddField(
            model_name='bidauction',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Auction'),
        ),
        migrations.AddField(
            model_name='bidauction',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
