# Generated by Django 2.1.2 on 2018-10-19 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_auto_20181019_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidauction',
            name='bid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='bidauction',
            name='highestBidder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 15, 25, 12, 752042)),
        ),
    ]
