# Generated by Django 2.1.2 on 2018-10-19 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_auto_20181019_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 15, 59, 6, 972506)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 15, 59, 6, 973506)),
        ),
    ]
