# Generated by Django 2.1.2 on 2018-10-19 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0008_auto_20181019_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidauction',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='highestBidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='highestBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newApp.BidAuction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 16, 34, 58, 560472)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 16, 34, 58, 560472)),
        ),
    ]
