# Generated by Django 2.1.2 on 2018-10-19 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0012_auto_20181019_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 19, 22, 6, 755557)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionBid', to='newApp.Auction'),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 19, 22, 6, 755557)),
        ),
    ]
