# Generated by Django 2.1.2 on 2018-10-21 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0013_auto_20181019_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.RenameField(
            model_name='bidauction',
            old_name='bid',
            new_name='current_bid',
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 42, 58, 217875)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='processqueue',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='newApp.Auction'),
        ),
        migrations.AddField(
            model_name='processqueue',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='newApp.BidAuction'),
        ),
    ]
