# Generated by Django 2.1.2 on 2018-10-21 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0015_auto_20181021_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidauction',
            old_name='current_bid',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 47, 25, 661674)),
        ),
    ]
