# Generated by Django 2.1.2 on 2018-10-21 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0018_auto_20181021_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 20, 28, 7, 975503)),
        ),
    ]
