# Generated by Django 2.1.2 on 2018-10-21 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0022_auto_20181021_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processqueue',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='processqueue',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='email_sent_time',
        ),
        migrations.AddField(
            model_name='bidauction',
            name='hasWon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 0, 45, 17, 422981)),
        ),
        migrations.DeleteModel(
            name='ProcessQueue',
        ),
    ]
