# Generated by Django 2.1.2 on 2018-10-21 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0023_auto_20181022_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 0, 50, 0, 155375)),
        ),
    ]
