# Generated by Django 2.1.2 on 2018-10-22 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0024_auto_20181022_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 13, 17, 23, 523667)),
        ),
    ]
