# Generated by Django 2.1.2 on 2018-10-22 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0025_auto_20181022_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 21, 23, 37, 50831)),
        ),
    ]
