# Generated by Django 2.1.2 on 2018-10-23 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0026_auto_20181022_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 13, 24, 19, 326607)),
        ),
    ]
