# Generated by Django 2.1.2 on 2018-10-23 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0030_auto_20181023_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 16, 8, 44, 60330)),
        ),
    ]
