# Generated by Django 2.1.2 on 2018-10-24 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0031_auto_20181023_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currencyConvert',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 19, 26, 6, 274446)),
        ),
    ]
