# Generated by Django 2.1.2 on 2018-10-24 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0032_auto_20181024_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='currencyConvert',
        ),
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 19, 59, 30, 731011)),
        ),
    ]
