# Generated by Django 2.1.2 on 2018-10-24 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0035_auto_20181024_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 2, 47, 44, 978566)),
        ),
    ]
