# Generated by Django 2.1.2 on 2018-10-25 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0036_auto_20181025_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 3, 9, 36, 83671)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='newApp.Auction'),
        ),
    ]
