# Generated by Django 2.1.2 on 2018-10-25 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0037_auto_20181025_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 3, 17, 9, 689750)),
        ),
    ]
