# Generated by Django 2.1.2 on 2018-10-25 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0039_auto_20181025_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 1, 56, 2, 492140)),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
