# Generated by Django 2.1.2 on 2018-10-28 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0042_auto_20181028_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 18, 23, 53, 667273)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish')], default='en', max_length=10),
        ),
    ]
